### ISSUE TITLE
Loading from files is far too slow

### ISSUE THREAD

**Issue by andrewlock** [andrewlock/PwnedPasswords#1]
If you have the full 12GB file, then searching through the file takes far too long to be acceptable in a web environment. 

Could look at parallelism, but I suspect that won't help the problem much. May have to enforce loading into memory (_big_ memory issue there) or add a DB service (I like this idea as an option anyway).

**Comment by SeanFarrow** [comment]
Hey Andrew,

Working on the database as that's what we're using, can't use files as we're writing a distributed application.
The only issue I have is do we mae ef core a part ofthis or split the lib in to 3 projects (contracts, core and ef)?
Regarding the reading of files I have an idea so will try to spike something tomorrow. Do you want me to fork, or are you happy to add me as a collaborator?

**Comment by andrewlock** [comment]
@SeanFarrow Just added you as a collaborator :)

I'd be interested to hear the exact use cases you have for this. In my mind I was thinking of the following:

1. The user just wants to call the HaveIBeenPwned API directly - no need to mess with the data, but limited by the 1500ms per call. Probably ok for most web apps
2. User wants to deploy the password files with the app and access directly, to avoid calling the API. Problem is the size of the files makes them prob untenable for loading into memory. Interested to hear your thoughts on that one!
3. Load the data into a DB and query directly using a custom `IHaveIBeenPwnedService` implementation.
4. Call a "mirror" of the HaveIBeenPwned API from the validator.

From my point of view, I'm most interested in the last point. I would stand up a simple ASP.NET Core web app that mirrors the semantics of Troy's public API, but is just reading from a DB etc. This would work best from the distributed app point of view, and means the Validator service doesn't need knowledge of any particular API etc.

I _think_ point 4. is prob also what you're after, though you're maybe describing 3.? 

In terms of architecture, I think if you want to have EF specific code in there, it will have to be a separate package. A bit annoying as we end up with many different projects, but prob the only way to avoid escalating dependencies. 

I'll try and put together the example mirror API in the next couple of days. I'll prob make it a simple middleware so that you can easily just drop it into any app, wire up an `IHaveIBeenPwnedService` and have everything just work.

**Comment by andrewlock** [comment]
Also, RE your comment about the strategy pattern - that's pretty much just being achieved using DI atm. Just register the `IHaveIBeenPwnedService` implementation (strategy) that you want, and it'll get injected into the Validator.

**Comment by SeanFarrow** [comment]
Currently looking at point 3, although 4 could be interesting!
I’ve got several api’s so it’s another microservice to deploy, plus given we’re using identity we already have a database.

**Comment by SeanFarrow** [comment]
Also, could you not use File.ReadLines and concat all lines in all files using linq, surely this would be usable?

**Comment by andrewlock** [comment]
The problem is that the files are 12GB - you can't really read that all that into memory for a web app (I physically can't on my dev machine, only 16GB memory!). Having said that, the file approach clearly doesn't work with files that size either!

**Comment by SeanFarrow** [comment]
Ok, should we can that and just have an api with a database behind it?
Either that or have a service as we have now with a strategy (which OOTB is a database). That way if people really want to implement the file based approach, with all its caveats,  they can.

**Comment by andrewlock** [comment]
Yeah, I think having the Validator use the API as the default option is best for the basic package. A separate package that implements an `IHaveBeenPwnedApiService` with a database on top of that covers use case 3, and then a separate package for creating your own HaveIBeenPwned API (that can be backed by a DB too).

**Comment by SeanFarrow** [comment]
Ok, I’ll start work on the database.
I’ll let you start work on the api.

**Comment by andrewlock** [comment]
@SeanFarrow I've created a PR #4 to add an API server that mirrors the HaveIBeenPwnedAPI. I had to rearrange things a bit. Did you want to take a look before I merge?

**Comment by SeanFarrow** [comment]
Hi,

Yes, please, give me a couple of days, just reformatting a machine!

**Comment by andrewlock** [comment]
Hi @SeanFarrow, it's been a long while since we looked at this!

Not sure if you've kept up to speed with Troy's changes and the anonymous endpoint? If not, it means passwords are never sent to the API server, there's no rate limit, and the speed is incredibly quick (<20ms). 

For me, that completely removes the need for the file/database APIs, and I'm thinking that will be true for most people. Frankly, I can't see the speed of a file-based service ever being sufficient, and the complexity of a database-based service being worth the (questionable) anonymity, performance or reliability gains.

I'm wondering how you feel about it? The project's been languishing here for a while, and updating to just wrap the API would definitely simplify things, and remove some of the issues. I'd like to push up a release to NuGet this weekend if possible

**Comment by SeanFarrow** [comment]
Hi,

I definitely agree.
Also, given that 2.1 is out and the benefits that brings with polly and retries, it makes sense to just create an API client to wrap the api.
I’ve been meaning to do this for a while, but am currently with a client and heading to Norway for NDC, so time is limited.
I did look at writing some code to splitthe  the file as troy does, but it took an age to run.
Hope that clarifies things.

**Comment by andrewlock** [comment]
Cool, that was exactly my thoughts too 👍  I'll put something together in the next couple of days. Hope you enjoy NDC, I'm sure it'll be excellent!

**Comment by andrewlock** [comment]
Put together a typed client for the PwnedPaswords api, and stripped out all the file/db side: #6

**Comment by SeanFarrow** [comment]
Ok, I’ll review tonight, we can then release tomorrow, hope this is OK?

**Comment by andrewlock** [comment]
Yeah sure, no rush 🙂

**Comment by SeanFarrow** [comment]
@AndrewLock, All looks good, so feel free to merge/release. I can't seem to find where this is used in the sample app though. There are a few spelling mistakes in comments, but they can be fixed after release--yes, I'm being picky.

It would be good to show the use of Polly in the sample app, again this can be done after the  release.

**Comment by SeanFarrow** [comment]
Given that we query the API, should we close this?

**Comment by andrewlock** [comment]
Yeah, agreed, I'll close 👍
