### ISSUE TITLE
Provide support for the new V3 API

### ISSUE THREAD

**Issue by SeanFarrow** [andrewlock/PwnedPasswords#21]
Given that V2 of the API has been deprecated, should we support V3?

This is the API requiring a key.

**Comment by andrewlock** [comment]
Yeah definitely, v2 will be shut off soon, so we need to do this. I'm happy to take a look, or defer to you? 🙂

**Comment by SeanFarrow** [comment]
Hi,

I’m happy to review a PR once you’ve finished this.
I think V2 has already gone, so was amazed this is still working.
Given this now costs, should we add a way for people to use an offline version of the database?

**Comment by andrewlock** [comment]
I looked into this again, as far as I can tell from [the docs](https://haveibeenpwned.com/API/v3#PwnedPasswords), V3 only applies to the haveIbeenpwned API, not the PwnedPasswords API. Which explains why there's been no complaints 🙂

**Comment by SeanFarrow** [comment]
Makes sense.
Feel free to close.
Or, should we extend this project to check for pwned Email addresses?

**Comment by andrewlock** [comment]
I believe there's already other libraries that handle the email/breach side of HaveIBeenPwnedApi, and I think it would complicate matters. I'm definitely inclined to keep this library as-is!
