### ISSUE TITLE
Seeding and updating hte database

### ISSUE THREAD

**Issue by SeanFarrow** [andrewlock/PwnedPasswords#3]
How do we want to initially seed the database and when new passwords are available what mechanism do we want to provide to allow updates to be applied? Given that EF doesn't support seeding in 2.0.

**Comment by andrewlock** [comment]
To be honest, I don't think that should be a concern for this library.  I think every user would want to go about it differently, so you're probably onto a loser to try and generalise it.

**Comment by andrewlock** [comment]
Obsolete thanks to #6 and the k-anonymity API
