### ISSUE TITLE
Allow setting frequency threshold for breached passwords

### ISSUE THREAD

**Issue by darshanrampatel** [andrewlock/PwnedPasswords#8]
It would be useful if there was an option to choose the frequency of how many times a password was breached (e.g. only reject passwords that have been breached > 20 times).

https://github.com/andrewlock/PwnedPasswords/blob/a2eb87dea7c046f86bdf5f2fb730a0a0ec2a022d/src/PwnedPasswords.Client/PwnedPasswordsClient.cs#L45

**Comment by andrewlock** [comment]
Thanks, sounds like a good idea to me🙂 I'll try and get this implemented today.

**Comment by andrewlock** [comment]
I have implemented the behaviour in a PR #9 - I'd be interested if that looks OK to you before I merge it and push a new package🙂

**Comment by darshanrampatel** [comment]
I have had a look and it looks great - thanks for getting to this so quickly!

Only thought I had was it might be worth updating the readme to show the option.

**Comment by andrewlock** [comment]
Good point, thanks! I'll get that updated and merged soon 🙂

**Comment by darshanrampatel** [comment]
Thanks!

**Comment by andrewlock** [comment]
No problem, thanks for the suggestion 🙂
